# Generated by Django 3.1.7 on 2021-03-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='media/trialPhoto/%Y/%m/%d/')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
